//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParveenEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventlog
    {
        public int Eventid { get; set; }
        public string Eventname { get; set; }
        public Nullable<System.DateTime> Eventtime { get; set; }
    }
}
