//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParveenEvent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Reg
    {

        public int Cus_Id { get; set; }
        public string Cus_Name { get; set; }
        public string Cus_Mobile { get; set; }
        public string Cus_Company { get; set; }
        public string Cus_Occupation { get; set; }
        public string IsPresent { get; set; }
        public string IsGift { get; set; }
        [Key]
        public int Cus_key { get; set; }
        public string Cus_Email { get; set; }
    }
}
